CREATE TABLE sanctioned_address (
    address     VARCHAR(64) PRIMARY KEY,
    entity      VARCHAR(255) NOT NULL,
    list_source VARCHAR(255) NOT NULL,
    program     VARCHAR(255) NOT NULL,
    severity    INTEGER NOT NULL
);

CREATE TABLE transaction_edge (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_address VARCHAR(64) NOT NULL,
    to_address   VARCHAR(64) NOT NULL,
    amount_usd   DOUBLE PRECISION NOT NULL,
    asset        VARCHAR(255) NOT NULL,
    tx_hash      VARCHAR(80) NOT NULL
);

CREATE INDEX idx_edge_from ON transaction_edge(from_address);
CREATE INDEX idx_edge_to ON transaction_edge(to_address);

CREATE TABLE tool_status (
    tool_id     VARCHAR(64) PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    enabled     BOOLEAN NOT NULL
);
