CREATE TABLE user_account (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                      VARCHAR(255) NOT NULL UNIQUE,
    password_hash                 VARCHAR(255),
    oidc_issuer                   VARCHAR(512),
    oidc_subject                  VARCHAR(512),
    email                         VARCHAR(320),
    totp_secret_encrypted         VARCHAR(1024),
    pending_totp_secret_encrypted VARCHAR(1024),
    pending_totp_expires_at       TIMESTAMP(6) WITH TIME ZONE,
    totp_last_counter             BIGINT,
    mfa_enrolled_at               TIMESTAMP(6) WITH TIME ZONE,
    role                          VARCHAR(255) NOT NULL,
    enabled                       BOOLEAN NOT NULL,
    created_at                    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_oidc_identity UNIQUE (oidc_issuer, oidc_subject)
);

CREATE TABLE authentication_challenge (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    user_id     BIGINT NOT NULL REFERENCES user_account(id),
    attempts    INTEGER NOT NULL,
    expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_authentication_challenge_user ON authentication_challenge(user_id);

CREATE TABLE passkey_credential (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES user_account(id),
    credential_id VARCHAR(2048) NOT NULL UNIQUE,
    public_key    VARCHAR(4096) NOT NULL,
    counter       BIGINT NOT NULL,
    transports    VARCHAR(256),
    device_type   VARCHAR(32) NOT NULL,
    backed_up     BOOLEAN NOT NULL,
    aaguid        VARCHAR(36),
    label         VARCHAR(80) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_used_at  TIMESTAMP(6) WITH TIME ZONE,
    version       BIGINT NOT NULL
);

CREATE INDEX idx_passkey_credential_user ON passkey_credential(user_id);

CREATE TABLE recovery_code (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES user_account(id),
    code_hash  VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX idx_recovery_code_user ON recovery_code(user_id);
