CREATE TABLE case_record (
    id                VARCHAR(64) PRIMARY KEY,
    subject_address   VARCHAR(64) NOT NULL,
    decision          VARCHAR(255) NOT NULL,
    risk_score        INTEGER NOT NULL,
    risk_band         VARCHAR(255) NOT NULL,
    summary           VARCHAR(4000) NOT NULL,
    risk_factors_json VARCHAR(8000),
    created_by        VARCHAR(255),
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE audit_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor      VARCHAR(255) NOT NULL,
    action     VARCHAR(255) NOT NULL,
    target     VARCHAR(255),
    detail     VARCHAR(4000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE screening_policy (
    policy_key  VARCHAR(64) PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    int_value   INTEGER NOT NULL
);
